name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.18.2'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake
        sudo apt-get install -y cmake
        cd /usr/src/gtest
        sudo cmake .
        sudo make
        sudo cp *.a /usr/lib
    - name: Install Google Benchmark
      run: |
        git clone https://github.com/google/benchmark.git
        cd benchmark
        git clone https://github.com/google/googletest.git
        mkdir build
        cd build
        cmake .. -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
        make
        sudo make install
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure
    - name: Run benchmarks
      run: |
        cd build
        ./benchmark_my_class
    - name: Generate documentation
      run: |
        doxygen Doxyfile
    - name: Deploy documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: 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
        publish_dir: ./docs
